#! /bin/bash

ze_netcdf=netcdf-4.0.1
#ze_netcdf=netcdf-3.6.1

#wget ftp://ftp.unidata.ucar.edu/pub/netcdf/$ze_netcdf.tar.gz
wget ftp://ftp.unidata.ucar.edu/pub/netcdf/old/$ze_netcdf.tar.gz
tar xzvf $ze_netcdf.tar.gz
\rm $ze_netcdf.tar.gz

export FC=gfortran
export FFLAGS=" -O2 -fPIC"
export F90=gfortran
export FCFLAGS="-O2 -ffree-form -fPIC"
export CPPFLAGS=""
export CC=gcc
export CFLAGS="-O2 -fPIC"
export CXX=g++
export CXXFLAGS="-O2 -fPIC"

mv $ze_netcdf gfortran_$ze_netcdf
cd gfortran_$ze_netcdf
PREFIX=$PWD
if [[ "$ze_netcdf" == "netcdf-3.6.1" ]]
then
      cd src
fi

./configure --prefix=${PREFIX} #--disable-cxx
make > make.log 2>&1
make test > make.log 2>&1
make install > make.log 2>&1
